[bumpver]
current_version = "2025.1"
version_pattern = "YYYY.INC0[-TAG]"
commit = false
tag = false
push = false

[bumpver.file_patterns]
"terrainbook.tex" = [
  'v{version}',
]
"docs/_config.yml" = [
  "latest_version: {version}",
]
"CITATION.bib" = [
  "year = {YYYY}",
]
"front-back/pre.tex" = [
  " YYYY % VER:YEAR",
]
