[bumpver]
current_version = "2023.0-beta"
version_pattern = "YYYY.MINOR[-TAG]"
commit = false
tag = false
push = false

[bumpver.file_patterns]
"terrainbook.tex" = [
    'v{version}',
]
"docs/_config.yml" = [
    "latest_version: {version}",
]



